# Numpy

In [1]:
import numpy as np



In [2]:
# one dimensional array
a=np.array([1,2])

In [3]:
print(a)

[1 2]


In [4]:
#two dimension array
b=np.array([[1,2,3,3],[3,4,3,4]],dtype=float)
print(b)

[[1. 2. 3. 3.]
 [3. 4. 3. 4.]]


In [5]:
#total no of element in array
b.size

8

In [6]:
#element size int=4 bytes float=8 bytes
b.itemsize

8

In [7]:
#convert row into column and column into row
b.transpose()

array([[1., 3.],
       [2., 4.],
       [3., 3.],
       [3., 4.]])

In [8]:
#type of array
b.dtype

dtype('float64')

In [9]:
#shows rows and columns of data
b.shape

(2, 4)

In [10]:
#multi dimensional array
s=np.array([[1,2],[2,3],[3,4]])
s

array([[1, 2],
       [2, 3],
       [3, 4]])

In [11]:
#print 0 in defined matrix
c=np.zeros((2,20))
c

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

In [12]:
#print one in defined matrix
d=np.ones((3,4))
d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
#arange is a method used to define a range in array
e=np.arange(2,10)
e

array([2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
a=np.array([[2,3,4,5],[3,4,5,6]])
a

array([[2, 3, 4, 5],
       [3, 4, 5, 6]])

In [15]:
#change the shape of row and column
a.reshape(4,2)

array([[2, 3],
       [4, 5],
       [3, 4],
       [5, 6]])

In [16]:
# convert all data in one row 
a.ravel()

array([2, 3, 4, 5, 3, 4, 5, 6])

In [17]:
a.sum()

32

In [18]:
a.max()

6

In [19]:
a.min()

2

In [20]:
a.mean()

4.0

In [21]:
a.sum(axis=0)

array([ 5,  7,  9, 11])

In [22]:
a.sum(axis=1)

array([14, 18])

In [23]:
b=np.sqrt(a)

In [24]:
b

array([[1.41421356, 1.73205081, 2.        , 2.23606798],
       [1.73205081, 2.        , 2.23606798, 2.44948974]])

# Mathematical Operations 

In [25]:
a=np.array([[1,2,3],[1,2,3]])
b=np.array([[1,2,3],[2,3,4]])


In [26]:
print(a)

[[1 2 3]
 [1 2 3]]


In [27]:
print(b)

[[1 2 3]
 [2 3 4]]


In [28]:
a+b

array([[2, 4, 6],
       [3, 5, 7]])

In [29]:
a-b

array([[ 0,  0,  0],
       [-1, -1, -1]])

In [30]:
a/b

array([[1.        , 1.        , 1.        ],
       [0.5       , 0.66666667, 0.75      ]])

In [31]:
a*b

array([[ 1,  4,  9],
       [ 2,  6, 12]])

# slicing in array

In [32]:
#one dimensional array
a=np.array([1,2,3,4,56,322,1])
print(a)

[  1   2   3   4  56 322   1]


In [33]:
a[1]

2

In [34]:
a[0:-1:2]

array([ 1,  3, 56])

In [35]:
a[2::-1]

array([3, 2, 1])

In [36]:
#multi dimensional array
b=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [37]:
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [38]:
b[2,1]

8

In [39]:
b[0:1,2]

array([3])

In [40]:
b[2,0:1]

array([7])

In [41]:
b[1,1]

5

In [42]:
b[-1]

array([7, 8, 9])

## iteration through array

In [43]:
#iteration through array
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
for c in b.flat:
    print(c)

1
2
3
4
5
6
7
8
9


In [45]:
ss=np.arange(6).reshape(2,3)
ss

array([[0, 1, 2],
       [3, 4, 5]])

In [83]:
for i in ss:
    for j in i:
        print(j)

0
1
2
3
4
5


In [78]:
#print row wise
for i in np.nditer(ss,order="C"):

    print(i)

0
1
2
3
4
5


In [80]:
#print column wise
for i in np.nditer(ss,order="F"):
    print(i)

0
3
1
4
2
5


## stacking

In [46]:
a=np.arange(6).reshape(3,2)

In [47]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [48]:
b=np.arange(25,31).reshape(3,2)

In [49]:
b

array([[25, 26],
       [27, 28],
       [29, 30]])

In [50]:
#it add b in a at row vise
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [25, 26],
       [27, 28],
       [29, 30]])

In [51]:
#it add b in a at column vise
np.hstack((a,b))

array([[ 0,  1, 25, 26],
       [ 2,  3, 27, 28],
       [ 4,  5, 29, 30]])

## spliting the array 

In [52]:
a=np.arange(30).reshape(5,6)
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [53]:
#it break into 3 sub arrays
c=np.hsplit(a,3)
c

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19],
        [24, 25]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21],
        [26, 27]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23],
        [28, 29]])]

In [54]:
c[0]

array([[ 0,  1],
       [ 6,  7],
       [12, 13],
       [18, 19],
       [24, 25]])

In [55]:
c[-1]

array([[ 4,  5],
       [10, 11],
       [16, 17],
       [22, 23],
       [28, 29]])

In [56]:
d=np.vsplit(a,5)

In [57]:
d

[array([[0, 1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23]]),
 array([[24, 25, 26, 27, 28, 29]])]

In [58]:
d[1]

array([[ 6,  7,  8,  9, 10, 11]])

## filter

In [59]:
a=np.arange(30).reshape(5,6)
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [60]:
b=a>4
b

array([[False, False, False, False, False,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [61]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29])

In [62]:
a[b]=-1

In [63]:
a

array([[ 0,  1,  2,  3,  4, -1],
       [-1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1]])

In [64]:
a=np.arange(30).reshape(5,6)
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [65]:
b=a+10
b

array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [66]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [67]:
np.savetxt('numpy.txt',a)

In [68]:
b=np.loadtxt('numpy.txt')

In [69]:
b

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.],
       [24., 25., 26., 27., 28., 29.]])